### ISSUE TITLE
Problem localization

### ISSUE THREAD

**Issue by thierryhoude** [Lexicality/Lexical-Tools#24]
Hello, I have a problem with the localization on my server I only have the gamemode darkrp and in addons darkrp modification and the moneypot up to date and the name, the description ECT... exemple: #tool.moneypot.name #tool.moneypot.desc #tool.moneypot.left ECT... im using french language in gmod (fr)

**Comment by Lexicality** [comment]
This happens sometimes and I genuinely don't know why, my best suggestion is reinstalling the addon
