### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by Jelman21** [Lexicality/Lexical-Tools#6]
1. enable to create fading door and link multiple keypads to that fading door, without the setting the button nonsense (like the other / original keypad tools)
1a. or, do some crazy crap to allow multiple keypads to be wired to a single door via wiremod
2. hook to enable you to specify jobs with a faster cracking speed (i think you can create custom weapons to do this already?)
3. make it make sound throughout the whole cracking process

**Comment by Lexicality** [comment]
#3 is your computer
